[package]
name = "dbt-extractor"
version = "0.2.0"
authors = ["Nathaniel May <nathaniel.may@fishtownanalytics.com>"]
edition = "2018"

[lib]
name = "dbt_extractor"
crate-type = ["cdylib", "lib"]

[dependencies]
tree-sitter = "0.19"
tree-sitter-jinja2 = { git = "git://github.com/fishtown-analytics/tree-sitter-jinja2", branch = "main" }
thiserror = "1.0.25"
pyo3 = { version = "0.13.2", features = ["extension-module"] }
